---
- name: Set VM hostname
  hostname:
    name: "{{ vm_name }}"

- name: Set VM hostname in /etc/hosts (Ubuntu/Debian)
  replace:
    path: /etc/hosts
    regexp: '(.*?)template$'
    replace: '\1{{ vm_name }}.private.vtluug.org {{ vm_name }}'
    backup: yes
  when: ansible_os_family == "Debian"

- name: Install selinux-python (Centos/Fedora)
  yum:
    name: libselinux-python
    state: latest
    disable_gpg_check: yes
  when: ansible_os_family == "RedHat"

- name: Set VM hostname in /etc/hosts (Centos/Fedora)
  lineinfile:
    path: /etc/hosts
    insertafter: EOF
    line: "{{ item }}"
    backup: yes
  with_items:
    - "{{ vm_ip }} {{ vm_name }}.private.vtluug.org {{ vm_name }} localhost.localdomain localhost"
    - "{{ vm_ip6 }} {{ vm_name }}.vtluug.org {{ vm_name }} localhost.localdomain localhost"
  when: ansible_os_family == "RedHat"

- name: Disable selinux (Centos/Fedora)
  selinux:
    state: disabled
  when: ansible_os_family == "RedHat"

- name: Reboot VM
  command: /sbin/reboot
