---
- hosts: proxmox
  become: yes
  handlers:
  - import_tasks: handlers/main.yml
  roles:
  - proxmox-common 
  - common

- hosts: debian
  become: yes
  handlers:
  - import_tasks: handlers/main.yml
  roles:
  - debian-common
  - common
  - freeipa-client

- hosts: nfs
  become: yes
  handlers:
  - import_tasks: handlers/main.yml
  roles:
  - nfs

- hosts: hpc
  become: yes
  roles:
#  - ubuntu-common
#  - common
  - amdgpu-pro
  - hpc

- hosts: freeipa
  become: yes
  roles:
  - freeipa

- hosts: web
  become: yes
  roles:
  - web

- hosts: shell
  become: yes
  roles:
  - mail
  - games

- hosts: log
  become: yes
  roles:
  - log

- hosts: jitsi
  become: yes
  roles:
  - jitsi

- hosts: emby
  become: yes
  roles:
  - emby

- hosts: mirror
  become: yes
  roles:
  - mirror

- hosts: syncthing
  become: yes
  roles:
  - syncthing

- hosts: tahoe-lafs
  become: yes
  roles:
  - tahoe-lafs

- hosts: wargame
  become: yes
  roles:
  - wargame

- hosts: map
  become: yes
  roles:
  - map
