---
# Distro groups
- hosts: ubuntu
  become: yes
  roles:
    - ubuntu-common
    - common
    - freeipa-client

- hosts: centos
  become: yes
  roles:
    - centos-common
    - common

# Bare-metal
- hosts: libvirt
  become: yes
  roles:
    - libvirt
    
- hosts: nfs
  become: yes
  roles:
    - nfs

# Important VMs
- hosts: freeipa
  become: yes
  roles:
    - freeipa-server

#- hosts: log
#  become: yes
#  roles:
#    - log
#
#- hosts: shell
#  become: yes
#  roles:
#    - mail
#    - games
#
#- hosts: web
#  become: yes
#  roles:
#    - web
#
## General VMs
#- hosts: emby
#  become: yes
#  roles:
#    - emby
#
#- hosts: jitsi
#  become: yes
#  roles:
#    - jitsi
#
#- hosts: map
#  become: yes
#  roles:
#    - map
#
#- hosts: mirror
#  become: yes
#  roles:
#    - mirror
#
#- hosts: syncthing
#  become: yes
#  roles:
#    - syncthing
#
#- hosts: tahoe-lafs
#  become: yes
#  roles:
#    - tahoe-lafs
#
#- hosts: wargame
#  become: yes
#  roles:
#    - wargame
