---
# Distro groups
- hosts: ubuntu
  become: yes
  roles:
    - ubuntu-common
    - freeipa-client
    - common

- hosts: centos
  become: yes
  roles:
    - centos-common
    - freeipa-client
    - common

# Bare-metal
- hosts: libvirt
  become: yes
  roles:
    - libvirt
    
- hosts: nfs
  become: yes
  roles:
    - nfs

# Important VMs
#- hosts: shell
#  become: yes
#  roles:
#    - shell
#
- hosts: web
  become: yes
  roles:
    - web

## General VMs
#- hosts: mirror
#  become: yes
#  roles:
#    - mirror
#
#- hosts: tahoe-lafs
#  become: yes
#  roles:
#    - tahoe-lafs
#
#- hosts: wargame
#  become: yes
#  roles:
#    - wargame
