---
- hosts: fileserver
  vars:
    config_zfs: "{{ CONFIG_ZFS|default('no') }}"
    confirm_zfs: "{{ CONFIRM_ZFS|default('no') }}"
  become: yes
  roles:
    - centos-common
    - common
    - prepare_zfs
  # Relies on user to create 'tank' properly
  # ASSUMES NEW INSTALLATION
  tasks:
    - name: Configure ZFS after pool creation
      include_role:
        name: configure_nfs
      tags:
        - configure_zfs
      when:
        - config_zfs == 'yes'
        - confirm_zfs == 'yes'
