---
# Distro groups
- hosts: proxmox
  become: yes
  handlers:
    - import_tasks: handlers/main.yml
  roles:
    - proxmox-common 
    - common

- hosts: ubuntu
  become: yes
  handlers:
    - import_tasks: handlers/main.yml
  roles:
    - ubuntu-common
    - common
    - freeipa-client
  vars_prompt:
    - name: "freeipa_password"
      prompt: "FreeIPA admin password (Only used for non-baremetal hosts)"

- hosts: centos
  become: yes
  roles:
    - centos-common
    - common

# Bare-metal
# Proxmox is bare-metal too, but it not the standard debian install so it gets
#   its own distro group
- hosts: nfs
  become: yes
  handlers:
    - import_tasks: handlers/main.yml
  roles:
    - nfs
    - common

# Important VMs
- hosts: freeipa
  become: yes
  roles:
    - freeipa-server
#
#- hosts: log
#  become: yes
#  roles:
#    - log
#
#- hosts: shell
#  become: yes
#  roles:
#    - mail
#    - games
#
#- hosts: web
#  become: yes
#  roles:
#    - web
#
## General VMs
#- hosts: emby
#  become: yes
#  roles:
#    - emby
#
#- hosts: jitsi
#  become: yes
#  roles:
#    - jitsi
#
#- hosts: map
#  become: yes
#  roles:
#    - map
#
#- hosts: mirror
#  become: yes
#  roles:
#    - mirror
#
#- hosts: syncthing
#  become: yes
#  roles:
#    - syncthing
#
#- hosts: tahoe-lafs
#  become: yes
#  roles:
#    - tahoe-lafs
#
#- hosts: wargame
#  become: yes
#  roles:
#    - wargame
