- hosts: debian
  user: root
  handlers:
  - include: handlers/mail.yml
  - include: handlers/ssh.yml
  vars:
  - include: vars/default.yml
  - include: vars/private.yml
  roles:
  - common
  - debian-common

- hosts: auth
  user: root
  handlers:
  - include: handlers/mail.yml
  - include: handlers/ssh.yml
  vars:
  - include: default.yml
  roles:
  - selinux
  - common
  - centos-common
  - ldap
  
  
- hosts: tor-relay
  user: root
  handlers:
  - include: handlers/mail.yml
  - include: handlers/ssh.yml
  vars:
  - include: vars/default.yml
  - include: vars/private.yml
  roles:
  - selinux
  - common
  - centos-common
  - tor-relay

- hosts: centos
  user: root
  handlers:
  - include: handlers/mail.yml
  - include: handlers/ssh.yml
  vars:
  - include: vars/default.yml
  - include: vars/private.yml
  roles:
  - selinux
  - common
  - centos-common 

- hosts: kvm
  user: root
  handlers:
  - include: handlers/mail.yml
  - include: handlers/ssh.yml
  vars:
  - include: vars/default.yml
  - include: vars/private.yml
  roles:
  - common
  - centos-common 
  - kvm

