---
# Distro groups
- hosts: ubuntu
  become: yes
  roles:
    - ubuntu-common
    - freeipa-client
    - common

- hosts: centos
  become: yes
  roles:
    - centos-common
    - freeipa-client
    - common

# Bare-metal
- hosts: libvirt
  become: yes
  roles:
    - libvirt
    
- hosts: nfs
  become: yes
  roles:
    - nfs

# Technically bare-matal + VMs but w/e
- hosts: docker
  become: yes
  roles:
    - docker

# Important VMs
- hosts: shell
  become: yes
  roles:
    - shell

## General VMs
#- hosts: mirror
#  become: yes
#  roles:
#    - mirror
#
#- hosts: tahoe-lafs
#  become: yes
#  roles:
#    - tahoe-lafs
#
#- hosts: wargame
#  become: yes
#  roles:
#    - wargame
