---
- name: Start and enable chronyd
  systemd:
    name: chronyd.service
    state: started
    enabled: yes

- name: Refresh sources
  apt:
    update_cache: yes

- name: Upgrade packages
  apt:
    upgrade: yes

- name: Restart unattended-upgrades
  systemd:
    name: unattended-upgrades.service
    state: restarted
