---
- name: Enable non-sub repo & Disable sub repo
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
  with_items:
    - { repo: 'deb http://download.proxmox.com/debian/pve stretch pve-no-subscription', state: present }
    - { repo: 'deb https://enterprise.proxmox.com/debian/pve stretch pve-enterprise',   state: absent }
  notify:
    - Update packages (Debian, Ubuntu)
    - Upgrade packages (Debian, Ubuntu)

- name: Disable 'No valid subscription' warning popup on the GUI
  replace:
    path: /usr/share/pve-manager/js/pvemanagerlib.js
    regexp: '^(.+?)data\.status !== \''Active\''(.+?)$'
    replace: '\1false\2'
    backup: yes
  notify: Restart pveproxy
