---
- name: Add nfs mounts to proxmox
  template:
    src: templates/storage.cfg.j2
    dest: /etc/pve/storage.cfg
    mode: 0640
  vars:
    mounts:
      - { type: dir,     storage_id: local,              properties: { disable: '', path: /var/lib/vz, content: 'backup,vztmpl,iso', maxfiles: 0, shared: 0 }}
      - { type: zfspool, storage_id: local-zfs,          properties: { disable: '', pool: rpool/data, content: 'rootdir,images', sparse: 1 }}
      - { type: nfs,     storage_id: cistern-images,     properties: { server: 10.98.0.7, export: /cistern/nfs/pve/images,     options: soft, content: images }}
      - { type: nfs,     storage_id: cistern-isos,       properties: { server: 10.98.0.7, export: /cistern/nfs/pve/isos,       options: soft, content: iso }}
      - { type: nfs,     storage_id: cistern-templates,  properties: { server: 10.98.0.7, export: /cistern/nfs/pve/templates,  options: soft, content: vztmpl }}
      - { type: nfs,     storage_id: tank-backup,        properties: { server: 10.98.0.6, export: /tank/nfs/pve/backup,        options: soft, content: backup }}
      - { type: nfs,     storage_id: keg-backup,         properties: { server: 10.98.0.8, export: /keg/nfs/pve/backup,         options: soft, content: backup }}
# Until dirtycow is up {{{
      - { type: nfs,     storage_id: temp-images,        properties: { server: 10.98.0.8, export: /keg/nfs/temp/pve/images,    options: soft, content: images }}
      - { type: nfs,     storage_id: temp-isos,          properties: { server: 10.98.0.8, export: /keg/nfs/temp/pve/isos,      options: soft, content: iso }}
      - { type: nfs,     storage_id: temp-templates,     properties: { server: 10.98.0.8, export: /keg/nfs/temp/pve/templates, options: soft, content: vztmpl }}
# }}}
  run_once: true
