---
- name: Configure Postfix relayhost
  replace:
    path: /etc/postfix/main.cf
    regexp: '^(relayhost =)$'
    replace: '\1 smtp.gmail.com'
    backup: yes
 
- name: Configure Postfix settings other than relayhost
  blockinfile:
    path: /etc/postfix/main.cf
    block: |
      smtp_use_tls = yes
      smtp_sasl_auth_enable = yes
      smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
      smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt
      smtp_sasl_security_options = noanonymous
      inet_protocols = ipv4
    backup: yes
  notify: Restart postfix
