---
- name: Create new VMs (meltdown)
  shell: |
    virt-builder
    "{{ item.os-version }}"
    --hostname "{{ item.hostname }}"
    --size 10G
    --format qcow2
    --output '/nfs/cistern/libvirt/meltdown/"{{ item.hostname }}".qcow2'
    --root-password password:"{{ root_password }}"
    --firstboot-command 'useradd -m -p "{{ papatux_password }}" papatux && usermod -aG "{{ item.admins }}" papatux'
    "{{ item.optional_args }}"
    &&
    virt-sysprep
    --add '/nfs/cistern/libvirt/meltdown/"{{ item.hostname }}".qcow2'
    --mac "{{ item.mac }}"
    --keep-user-accounts papatux
    &&
    virsh setvcpus "{{ item.hostname }}" "{{ item.cpus }}" --config
    &&
    virsh setmaxmem "{{ item.hostname }}" "{{ item.ram }}" --config
    &&
    virsh setmem "{{ item.hostname }}" "{{ item.ram }}" --config
    &&
    virsh autostart "{{ item.hostname }}"
    &&
    virsh start "{{ item.hostname }}"
  args:
      creates: '/nfs/cistern/libvirt/meltdown/"{{ item.hostname }}".qcow2'
  with_items: "{{ new_vms_meltdown }}"
  when: inventory_hostname == 'meltdown.private.vtluug.org'

- name: Create new VMs (spectre)
  shell: |
    virt-builder
    "{{ item.os-version }}"
    --hostname "{{ item.hostname }}"
    --size 10G
    --format qcow2
    --output '/nfs/cistern/libvirt/spectre/"{{ item.hostname }}".qcow2'
    --root-password password:"{{ root_password }}"
    --firstboot-command 'useradd -m -p "{{ papatux_password }}" papatux && usermod -aG "{{ item.admins }}" papatux'
    "{{ item.optional_args }}"
    &&
    virt-sysprep
    --add '/nfs/cistern/libvirt/spectre/"{{ item.hostname }}".qcow2'
    --mac "{{ item.mac }}"
    --keep-user-accounts papatux
    &&
    virsh setvcpus "{{ item.hostname }}" "{{ item.cpus }}" --config
    &&
    virsh setmaxmem "{{ item.hostname }}" "{{ item.ram }}" --config
    &&
    virsh setmem "{{ item.hostname }}" "{{ item.ram }}" --config
    &&
    virsh autostart "{{ item.hostname }}"
    &&
    virsh start "{{ item.hostname }}"
  args:
      creates: '/nfs/cistern/libvirt/spectre/"{{ item.hostname }}".qcow2'
  with_items: "{{ new_vms_spectre }}"
  when: inventory_hostname == 'spectre.private.vtluug.org'
