---
- name: Create new VMs (meltdown)
  shell: |
    virt-builder \
        {{ item.os }} \
        --hostname {{ item.hostname }} \
        --size 10G \
        --format qcow2 \
        --output /nfs/cistern/libvirt/images/meltdown/{{ item.hostname }}.qcow2 \
        --root-password password:"{{ root_pass }}" \
        --firstboot-command 'yum -y install openssl; systemctl disable firewalld; systemctl disable apparmor; sed -i "s/SELINUX=enforcing/SELINUX=disabled/" /etc/selinux/config; sed -i "s/#Port 22/Port 22\nPort 2222/" /etc/ssh/sshd_config; useradd -m -p $(openssl passwd -1 "{{ admin_pass }}") papatux && usermod -aG {{ item.admins }} papatux; reboot' \
    && \
    virt-install \
        --import \
        --name {{ item.hostname }} \
        --vcpus {{ item.cpus }} \
        --ram {{ item.ram }} \
        --network bridge=br0,mac={{ item.mac }} \
        --disk path=/nfs/cistern/libvirt/images/meltdown/{{ item.hostname }}.qcow2,format=qcow2 \
        --os-variant rhel7 \
        --autostart \
        --graphics spice \
        --noautoconsole
  args:
      creates: '/nfs/cistern/libvirt/meltdown/{{ item.hostname }}.qcow2'
  with_items: "{{ new_vms_meltdown }}"
  when: inventory_hostname == 'meltdown.vtluug.org'

- name: Create new VMs (spectre)
  shell: |
    virt-builder \
        {{ item.os }} \
        --hostname {{ item.hostname }} \
        --size 10G \
        --format qcow2 \
        --output /nfs/cistern/libvirt/images/spectre/{{ item.hostname }}.qcow2 \
        --root-password password:"{{ root_pass }}" \
        --firstboot-command 'yum -y install openssl; systemctl disable firewalld; systemctl disable apparmor; sed -i "s/SELINUX=enforcing/SELINUX=disabled/" /etc/selinux/config; sed -i "s/#Port 22/Port 22\nPort 2222/" /etc/ssh/sshd_config; useradd -m -p $(openssl passwd -1 "{{ admin_pass }}") papatux && usermod -aG {{ item.admins }} papatux; reboot' \
    && \
    virt-install \
        --import \
        --name {{ item.hostname }} \
        --vcpus {{ item.cpus }} \
        --ram {{ item.ram }} \
        --network bridge=br0,mac={{ item.mac }} \
        --disk path=/nfs/cistern/libvirt/images/spectre/{{ item.hostname }}.qcow2,format=qcow2 \
        --os-variant rhel7 \
        --autostart \
        --graphics spice \
        --noautoconsole
  args:
      creates: '/nfs/cistern/libvirt/spectre/{{ item.hostname }}.qcow2'
  with_items: "{{ new_vms_spectre }}"
  when: inventory_hostname == 'spectre.vtluug.org'

