---
- name: Deploy VMs
  proxmox_kvm_vtluug:
    api_user: root@pam
    api_password: "{{ proxmox_password }}"
    api_host: meltdown.private.vtluug.org
    node: "{{ item.node }}"
    target: "{{ item.target }}"
    clone: "{{ item.clone }}"
    name: "{{ item.name }}"
    net: "{ 'virtio': {{ item.mac }}, 'bridge': 'vmbr0' }"
    full: yes
    storage: temp-images
    timeout: 500
  with_items: "{{ new_vms }}"
  register: vminfo
  run_once: true

- name: Pause a bit since a bunch of VMs were just created
  pause:
    seconds: 60
  run_once: true


- name: Start recently created VMs
  proxmox_kvm_vtluug:
    api_user: root@pam
    api_password: "{{ proxmox_password }}"
    api_host: meltdown.private.vtluug.org
    node: "{{ item.item.target }}"
    name: "{{ item.item.name }}"
    state: started
  with_items: "{{ vminfo.results }}"
  when: item.changed == True
  run_once: true

- name: Wait for VMs to start (+ a reboot for new machine-id to take effectr; and centos can take a looong time)
  pause:
    minutes: 5
  run_once: true

- name: Add newly created VMs to group so we can set hostnames
  add_host:
    name: "{{ item.stdout }}"
    groups: new_vms
    vm_name: "{{ item.item.item.name }}"
    vm_ip: "{{ item.item.item.ip }}"
    vm_ip6: "{{ item.item.item.ip6 }}"
    vm_clone: "{{ item.item.item.clone }}"
  with_items: "{{ ipinfo.results }}"
  when: item.changed == True
  run_once: true
