---
- name: restart nfs
  systemd:
    name: nfs-kernel-server.service
    state: restarted

- name: Start and enable krb_mkhomedir
  systemd:
    name: krb_mkhomedir.timer
    state: started
    enabled: yes

- name: Start and enable scratch_deletion
  systemd:
    name: krb_mkhomedir.timer
    state: started
    enabled: yes
