---
- name: Install common packages
  apt:
    pkg:
      - chrony
      - curl
      - fail2ban
      - finger
      - freeipa-client
      - git
      - htop
      - iodine
      - man
      - mosh
      - nfs-common
      - nmap
      - screen
      - tmux
      - tor
      - unattended-upgrades
      - vim
      - wget
      - zsh
    state: latest
  notify:
    - Refresh sources
    - Upgrade packages
    
- name: Configure unattended-upgrades
  template:
    src: templates/50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: Restart unattended-upgrades
