---
- name: Install common packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - chrony
    - curl
    - freeipa-client
    - git
    - htop
    - man
    - nmap
    - tmux
    - vim
    - wget
    - zsh
