---
- name: Install libvirt packages
  apt:
    name: "{{ item }}"
  with_items:
    - qemu-kvm
    - libguestfs-tools
    - libvirt-daemon-system
    - libvirt-clients
    - python3-lxml
    - python3-libvirt
    - virtinst
  notify:
    - Add papatux to libvirt group
# TODO ensure libvirt autostarts on boot?
