---
- name: Configure libvirt storage pools
  virt_pool:
    state: "{{ item.state }}"
    name: "{{ item.name }}"
    autostart: "{{ item.autostart }}"
    xml: "{{ item.xml }}"
  with_items:
    - { state: deleted, name: default, autostart: no, xml: ''}
    - { state: active, name: isos, autostart: yes, xml: '/nfs/cistern/libvirt/isos' }

- name: Add images storage pool (meltdown)
  virt_pool:
    state: active
    name: cistern-md-images
    autostart: yes
    xml: '/nfs/cistern/libvirt/images/meltdown'
  when: inventory_hostname == 'meltdown.private.vtluug.org'

- name: Add images storage pool (spectre)
  virt_pool:
    state: active
    name: cistern-sp-images
    autostart: yes
    xml: '/nfs/cistern/libvirt/images/spectre'
  when: inventory_hostname == 'spectre.private.vtluug.org'
