---
- name: Create isos pool
  shell: |
    virsh pool-define-as isos --type dir --target /nfs/cistern/libvirt/isos
    virsh pool-autostart isos
    virsh pool-start isos
  args:
    creates: /etc/libvirt/storage/isos.xml

- name: Add images storage pool (meltdown)
  shell: |
    virsh pool-define-as cistern-md-images --type dir --target /nfs/cistern/libvirt/images/meltdown
    virsh pool-autostart cistern-md-images
    virsh pool-start cistern-md-images
  args:
    creates: /etc/libvirt/storage/cistern-md-images.xml
  when: inventory_hostname == 'meltdown.vtluug.org'

- name: Add images storage pool (spectre)
  shell: |
    virsh pool-define-as cistern-sp-images --type dir --target /nfs/cistern/libvirt/images/spectre
    virsh pool-autostart cistern-sp-images
    virsh pool-start cistern-sp-images
  args:
    creates: /etc/libvirt/storage/cistern-sp-images.xml
  when: inventory_hostname == 'spectre.vtluug.org'
