network:
  version: 2
  renderer: networkd
  ethernets:
    ens18:
      dhcp4: no
      addresses: [{{ ip }}/16]
      gateway4: 10.98.0.1
      namservers:
        addresses: [10.98.0.1,198.82.247.66]
