---
# REFERNCE:
# cyberdelia = tank = 10.98.0.6
# dirtycow = cistern = 10.98.0.7
# shellshock = keg = 10.98.0.8
######################################################
- name: Configure NFS exports {{ inventory_hostname }}
  import_role:
    name: geerlingguy.nfs
  vars:
    nfs_exports:
      - /tank/nfs/share      -rw,no_subtree_check 10.98.0.0/16  # All hosts
      - /tank/nfs/scratch    -rw,no_subtree_check,no_root_squash 10.98.0.0/16 # All hosts
  when: inventory_hostname == 'cyberdelia.vtluug.org'
  notify: restart nfs

- name: Configure NFS exports {{ inventory_hostname }}
  import_role:
    name: geerlingguy.nfs
  vars:
    nfs_exports:
      - /cistern/nfs/docker/data    -rw,no_subtree_check,no_root_squash 10.98.0.0/24 # All main hosts
      - /cistern/nfs/libvirt        -rw,no_subtree_check,no_root_squash 10.98.0.0/24 # All main hosts
      - /cistern/nfs/home           -rw,no_subtree_check 10.98.0.0/24 # All main hosts
      - /cistern/nfs/srv            -rw,no_subtree_check 10.98.0.11 # sczi
      - /cistern/nfs/files          -rw,no_subtree_check 10.98.0.0/16 # All hosts
      - /cistern/nfs/share          -rw,no_subtree_check 10.98.0.0/16 # All hosts
  when: inventory_hostname == 'dirtycow.vtluug.org'
  notify: restart nfs

- name: Configure NFS exports {{ inventory_hostname }}
  import_role:
    name: geerlingguy.nfs
  vars:
    nfs_exports:
      - /keg/nfs/share      -rw,no_subtree_check 10.98.0.0/16 # All hosts
  when: inventory_hostname == 'shellshock.vtluug.org'
  notify: restart nfs
