---
- name: Configure NFS exports {{ inventory_hostname }}
  import_role:
    name: geerlingguy.nfs
  vars:
    nfs_exports:
      - /cistern/nfs               -rw,no_subtree_check,no_root_squash 10.98.0.3/16 10.98.0.4/16 10.98.0.5/16  # meltdown spectre phantomphreak
      - /cistern/nfs/pve           -rw,no_subtree_check,no_root_squash 10.98.0.3/16 10.98.0.4/16 10.98.0.5/16  # meltdown spectre phantomphreak
      - /cistern/nfs/pve/images    -rw,no_subtree_check,no_root_squash 10.98.0.3/16 10.98.0.4/16 10.98.0.5/16  # meltdown spectre phantomphreak
      - /cistern/nfs/pve/isos      -rw,no_subtree_check,no_root_squash 10.98.0.3/16 10.98.0.4/16 10.98.0.5/16  # meltdown spectre phantomphreak
      - /cistern/nfs/pve/templates -rw,no_subtree_check,no_root_squash 10.98.0.3/16 10.98.0.4/16 10.98.0.5/16  # meltdown spectre phantomphreak
      - /cistern/nfs/home          -rw,no_subtree_check,no_root_squash 10.98.0.3/16 10.98.0.4/16 10.98.0.5/16  # meltdown spectre phantomphreak <VMs> TODO
      - /cistern/nfs/scratch       -rw,no_subtree_check,no_root_squash 10.98.0.3/16 10.98.0.4/16 10.98.0.5/16  # meltdown spectre phantomphreak <VMs> TODO
  when: inventory_hostname == 'dirtycow.private.vtluug.org'

- name: Configure NFS exports {{ inventory_hostname }}
  import_role:
    name: geerlingguy.nfs
  vars:
    nfs_exports:
      - /tank/nfs                       -rw,no_subtree_check,no_root_squash 10.98.0.3/16 10.98.0.4/16 10.98.0.5/16  # meltdown spectre phantomphreak <VMs> TODO
      - /tank/nfs/backup                -rw,no_subtree_check,no_root_squash 10.98.0.3/16 10.98.0.4/16 10.98.0.5/16  # meltdown spectre phantomphreak <VMs> TODO
      - /tank/nfs/scratch               -rw,no_subtree_check,no_root_squash 10.98.0.3/16 10.98.0.4/16 10.98.0.5/16  # meltdown spectre phantomphreak <VMs> TODO
  when: inventory_hostname == 'cyberdelia.private.vtluug.org'

- name: Configure NFS exports {{ inventory_hostname }}
  import_role:
    name: geerlingguy.nfs
  vars:
    nfs_exports:
      - /keg/nfs                        -rw,no_subtree_check,no_root_squash 10.98.0.3/16 10.98.0.4/16 10.98.0.5/16  # meltdown spectre phantomphreak <VMs> TODO
      - /keg/nfs/backup                 -rw,no_subtree_check,no_root_squash 10.98.0.3/16 10.98.0.4/16 10.98.0.5/16  # meltdown spectre phantomphreak <VMs> TODO
      - /keg/nfs/scratch                -rw,no_subtree_check,no_root_squash 10.98.0.3/16 10.98.0.4/16 10.98.0.5/16  # meltdown spectre phantomphreak <VMs> TODO
# Until dirtycow is up {{{
      - /keg/nfs/temp                   -rw,no_subtree_check,no_root_squash 10.98.0.3/16 10.98.0.4/16 10.98.0.5/16  # meltdown spectre phantomphreak
      - /keg/nfs/temp/pve               -rw,no_subtree_check,no_root_squash 10.98.0.3/16 10.98.0.4/16 10.98.0.5/16  # meltdown spectre phantomphreak
      - /keg/nfs/temp/pve/images        -rw,no_subtree_check,no_root_squash 10.98.0.3/16 10.98.0.4/16 10.98.0.5/16  # meltdown spectre phantomphreak
      - /keg/nfs/temp/pve/isos          -rw,no_subtree_check,no_root_squash 10.98.0.3/16 10.98.0.4/16 10.98.0.5/16  # meltdown spectre phantomphreak
      - /keg/nfs/temp/pve/templates     -rw,no_subtree_check,no_root_squash 10.98.0.3/16 10.98.0.4/16 10.98.0.5/16  # meltdown spectre phantomphreak
      - /keg/nfs/temp/home              -rw,no_subtree_check,no_root_squash 10.98.0.3/16 10.98.0.4/16 10.98.0.5/16  # meltdown spectre phantomphreak <VMs> TODO
# }}}
  when: inventory_hostname == 'shellshock.private.vtluug.org'

