---
- name: Deploy systemd timer to delete scratch contents
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
    backup: yes
  with_items:
    - { src: 'files/scratch_deletion.service', dest: '/etc/systemd/system/scratch_deletion.service', mode: '0644' }
    - { src: 'files/scratch_deletion.timer',   dest: '/etc/systemd/system/scratch_deletion.timer',   mode: '0644' }
  notify: Start and enable scratch_deletion
  when: inventory_hostname == 'cyberdelia.vtluug.org'

- name: Add deletion warning to scratch
  file:
    path: /tank/nfs/scratch/CONTENTS_IN_THIS_DIRECTORY_ARE_WIPED_ON_THE_FIRST_OF_EVERY_MONTH
    owner: root
    group: root
    mode: '0644'
    state: touch
  when: inventory_hostname == 'cyberdelia.vtluug.org'
  tags: needs_freeipa
