---
# Converts '7.4.1708' to '7_4'
- set_fact:
    fixed_version={{ '_'.join(ansible_distribution_version.split('.')[:-1]) }}

- name: Download ZFS package - CentOS 7
  get_url:
    url=http://download.zfsonlinux.org/epel/zfs-release.el{{ fixed_version }}.noarch.rpm
    dest=/tmp/zfs-release.el{{ fixed_version }}.noarch.rpm
    mode=0400

- name: Enable ZFS - CentOS 7
  command: rpm -Uvh /tmp/zfs-release.el7_4.noarch.rpm creates=/etc/yum.repos.d/zfs.repo

- name: Import ZFS signing key - CentOS 7
  rpm_key:
    key=/etc/pki/rpm-gpg/RPM-GPG-KEY-zfsonlinux

- name: Enable kABI-tracking kmod - CentOS 7.4
  patch:
    src: zfs-release.el7_4.noarch.rpm.patch
    dest: /etc/yum.repos.d/zfs.repo
  when: ansible_distribution_version == "7.4"

- name: Install ZFS - CentOS 7
  yum:
    name=zfs
    state=present
