---
- name: Enroll host in krb.vtluug.org domain
  shell: |
    ipa-client-install \
        --unattended \
        --domain=krb.vtluug.org \
        --server=chimera.vtluug.org \
        --principal=admin \
        --password={{ ipa_admin_pass }};
  args:
    creates: /etc/ipa/default.conf
  when:
    - "'baremetal' not in group_names"
    - inventory_hostname not in ['chimera.vtluug.org', 'sphinx.vtluug.org']
  tags: needs_freeipa
