- name: Setup authconfig
  command: authconfig --enableldap --disableldapauth --ldapserver=blade.vtluug.org --ldapbasedn=dc=vtluug,dc=org --disableldaptls --enablekrb5 --krb5kdc=blade.vtluug.org --krb5adminserver=blade.vtluug.org --krb5realm=VTLUUG.ORG --enablesssd --enablesssdauth --disablecache --enablelocauthorize --enablemkhomedir --update
