---
- name: Disable firewalld
  systemd:
    name: firewalld.service
    state: stopped
    enabled: no

- name: Disable Selinux
  selinux:
    state: disabled
  register: task_result

- name: Reboot if selinux status changed
  command: 'sleep 5 && reboot'
  when: task_result is changed

- name: Wait for reboot to finish (if selinux status changed)
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: task_result is changed
