---
- name: Enable EPEL - CentOS 7
  yum:
    name=epel-release
    state=present
  when: ansible_distribution_version.split(".")[0] == "7"
  tags:
  - common

- name: Import EPEL signing key - CentOS 7
  rpm_key:
    key=/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
  when: ansible_distribution_version.split(".")[0] == "7"
  tags:
  - common

- name: Install common packages
  yum:
    name={{ item }}
    state=present
  with_items:
  - git
  - htop
  - vim
  - tmux
  - ntp
  - ntpdate
  - ntp-doc
  - patch
  tags:
  - packages
  - common
