---
- name: Install common packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - chrony
    - freeipa-client
    - nfs-utils
    - tmux
    - vim
    - yum-cron
  notify:
    - Start and enable chronyd
    - Start and enable yum-cron
