---
# Only required for fail2ban
- name: Install epel-release (before other packages)
  yum:
    pkg:
      - epel-release
    state: latest

- name: Install common packages
  yum:
    pkg:
      - chrony
      - fail2ban
      - freeipa-client
      - nfs-utils
      - tmux
      - vim
      - dnf-automatic
    state: latest
  notify:
    - Start and enable chronyd
    - Start and enable dnf-automatic
