---
- name: Restart chronyd
  systemd:
    name: chronyd.service
    state: restarted

- name: Restart fail2ban
  systemd:
    name: fail2ban.service
    state: restarted

- name: Apply netplan config
  command: /usr/sbin/netplan apply

- name: Restart networking (Ubuntu)
  systemd:
    name: systemd-networkd.service
    state: restarted

- name: Restart networking (RedHat)
  systemd:
    name: network
    state: restarted

- name: Restart sshd
  systemd:
    name: sshd.service
    state: restarted
