---
- name: Start ntpd service
  service:
  	name=ntpd
  	state=started

- name: Stop ntpd service
  service:
  	name=ntpd
  	state=stopped

- name: Restart ntpd
  service:
  	name=ntpd
  	state=restarted

- name: Enable ntpd service
  service:
  	name=ntpd
  	enabled=yes
