---
- name: Start and enable chronyd
  systemd:
    name: chronyd.service
    state: started
    enabled: yes

- name: Start and enable dnf-automatic
  systemd:
    name: dnf-automatic.timer
    state: started
    enabled: yes

- name: Restart dnf-automatic
  systemd:
    name: dnf-automatic.timer
    state: restarted
