---
- name: Start and enable chronyd
  systemd:
    name: chronyd.service
    state: started
    enabled: yes

- name: Start and enable yum-cron
  systemd:
    name: yum-cron.service
    state: started
    enabled: yes

- name: Restart yum-cron
  systemd:
    name: yum-cron.service
    state: restarted
