---
- name: Install Docker prerequisites
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: latest

- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable

- name: Install Docker & docker-compose
  apt:
    pkg:
      - docker-ce
      - docker-compose
    state: latest

- name: Pull github.com/vtluug/apps
  git:
    repo: 'https://github.com/vtluug/apps.git'
    dest: /nfs/cistern/docker/apps

- name: Deploy systemd timer to prune old docker things
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
    backup: yes
  with_items:
    - { src: 'files/docker_cleanup.service', dest: '/etc/systemd/system/docker_cleanup.service', mode: '0644' }
    - { src: 'files/docker_cleanup.timer',   dest: '/etc/systemd/system/docker_cleanup.timer',   mode: '0644' }
  notify: Start and enable docker_cleanup
