---
- name: Configure Chrony
  template:
    src: templates/chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0544'
    backup: yes
  notify: Restart chronyd
  when: ansible_os_family == 'RedHat'

- name: Configure Chrony
  template:
    src: templates/chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: '0544'
    backup: yes
  notify: Restart chronyd
  when: ansible_os_family == 'Debian'
