---
# REFERNCE:
# cyberdelia = tank = 10.98.0.6
# dirtycow = cistern = 10.98.0.7
# shellshock = keg = 10.98.0.8
######################################################
# Note: mounts are organized by importance, then by IP
# Note2: Proxmox cluster nfs conf are in role proxmox-common/tasks/nfs.yml
- name: Create NFS mountpoints (All hosts)
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - { path: '/nfs',               owner: 'root',      group: 'root',  mode: '0755' }
    - { path: '/nfs/tank',          owner: 'root',      group: 'root',  mode: '0755' }
    - { path: '/nfs/tank/share',    owner: 'nfsnobody', group: 'users', mode: '0775' }
    - { path: '/nfs/tank/scratch',  owner: 'root',      group: 'root',  mode: '0777' }
    - { path: '/nfs/cistern',       owner: 'root',      group: 'root',  mode: '0755' }
    - { path: '/nfs/cistern/share', owner: 'nfsnobody', group: 'users', mode: '0775' }
    - { path: '/nfs/keg',           owner: 'root',      group: 'root',  mode: '0755' }
    - { path: '/nfs/keg/share',     owner: 'nfsnobody', group: 'users', mode: '0775' }
    - { path: '/nfs/keg/scratch',   owner: 'root',      group: 'root',  mode: '0777' }

- name: Create NFS mountpoints (All hosts EXCEPT Proxmox)
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - { path: '/nfs/cistern/files', owner: 'www-data', group: 'www-data', mode: '755' }
  when: "'proxmox' not in group_names"

- name: Create NFS mountpoints (Sczi)
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - { path: '/nfs/cistern/srv', owner: 'root', group: 'root', mode: '755' }
  when: inventory_hostname == 'sczi.private.vtluug.org'
