---
# REFERNCE:
# cyberdelia = tank = 10.98.0.6
# dirtycow = cistern = 10.98.0.7
# shellshock = keg = 10.98.0.8
######################################################
- name: Create NFS mountpoints (All hosts)
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - { path: '/nfs',               owner: 'root',     group: 'root',     mode: 0755 }
    - { path: '/nfs/tank',          owner: 'root',     group: 'root',     mode: 0755 }
    - { path: '/nfs/tank/share',    owner: 'root',     group: 'users',    mode: 0775 }
    - { path: '/nfs/tank/scratch',  owner: 'root',     group: 'root',     mode: 0777 }
    - { path: '/nfs/cistern',       owner: 'root',     group: 'root',     mode: 0755 }
    - { path: '/nfs/cistern/share', owner: 'root',     group: 'users',    mode: 0775 }
    - { path: '/nfs/cistern/files', owner: 'www-data', group: 'www-data', mode: 0755 }
    - { path: '/nfs/keg',           owner: 'root',     group: 'root',     mode: 0755 }
    - { path: '/nfs/keg/share',     owner: 'root',     group: 'users',    mode: 0775 }

- name: Create NFS mountpoints (Libvirt)
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - { path: '/nfs/cistern/libvirt',                 owner: 'root', group: 'root', mode: 0755 }
    - { path: '/nfs/cistern/libvirt/images',          owner: 'root', group: 'root', mode: 0755 }
    - { path: '/nfs/cistern/libvirt/images/meltdown', owner: 'root', group: 'root', mode: 0755 }
    - { path: '/nfs/cistern/libvirt/images/spectre',  owner: 'root', group: 'root', mode: 0755 }
    - { path: '/nfs/cistern/libvirt/isos',            owner: 'root', group: 'root', mode: 0755 }
  when: "'libvirt' in group_names"

- name: Create NFS mountpoints (Sczi)
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - { path: '/nfs/cistern/srv', owner: 'root', group: 'root', mode: 0755 }
  when: inventory_hostname == 'sczi.private.vtluug.org'
