---
- name: Configure global IPv4 addrs (Non-libvirt hosts, Ubuntu)
  template:
    src: templates/01-netcfg.yaml.j2
    dest: /etc/netplan/01-netcfg.yaml
    owner: root
    group: root
    mode: '0644'
  notify:
    - Apply netplan config
    - Restart networking (Ubuntu)
  when:
    - global_v4 is defined
    - ansible_distribution == 'Ubuntu'
    - "'libvirt' not in group_names"
