---
# REFERNCE:
# cyberdelia = tank = 10.98.0.6
# dirtycow = cistern = 10.98.0.7
# shellshock = keg = 10.98.0.8
######################################################
- name: Mount NFS (All but storage hosts)
  mount:
    src: "{{ item.filesystem }}"
    path: "{{ item.mountpoint }}"
    fstype: "{{ item.type }}"
    opts: "{{ item.options }}"
    state: mounted
  with_items:
    - { filesystem: '10.98.0.6:/tank/nfs/share',    mountpoint: '/nfs/tank/share',    type: 'nfs', options: 'vers=4.0,soft,nodev,nosuid', dump: '0', pass: '0' }
    - { filesystem: '10.98.0.6:/tank/nfs/scratch',  mountpoint: '/nfs/tank/scratch',  type: 'nfs', options: 'vers=4.0,soft,nodev,nosuid', dump: '0', pass: '0' }
    - { filesystem: '10.98.0.7:/cistern/nfs/home',  mountpoint: '/nfs/cistern/home',  type: 'nfs', options: 'vers=4.0,soft,nodev',        dump: '0', pass: '0' }
    - { filesystem: '10.98.0.7:/cistern/nfs/files', mountpoint: '/nfs/cistern/files', type: 'nfs', options: 'vers=4.0,soft,nodev,nosuid', dump: '0', pass: '0' }
    - { filesystem: '10.98.0.7:/cistern/nfs/share', mountpoint: '/nfs/cistern/share', type: 'nfs', options: 'vers=4.0,soft,nodev,nosuid', dump: '0', pass: '0' }
    - { filesystem: '10.98.0.8:/keg/nfs/share',     mountpoint: '/nfs/keg/share',     type: 'nfs', options: 'vers=4.0,soft,nodev,nosuid', dump: '0', pass: '0' }
  when: "'nfs' not in group_names"
  tags: needs_freeipa

- name: Mount NFS (Libvirt hosts)
  mount:
    src: "{{ item.filesystem }}"
    path: "{{ item.mountpoint }}"
    fstype: "{{ item.type }}"
    opts: "{{ item.options }}"
    state: mounted
  with_items:
    - { filesystem: '10.98.0.7:/cistern/nfs/libvirt', mountpoint: '/nfs/cistern/libvirt', type: 'nfs', options: 'vers=4.0,soft,nodev,nosuid', dump: '0', pass: '0' }
  when: "'libvirt' in group_names"

- name: Mount NFS  (Cyberdelia)
  mount:
    src: "{{ item.filesystem }}"
    path: "{{ item.mountpoint }}"
    fstype: "{{ item.type }}"
    opts: "{{ item.options }}"
    state: present
  with_items:
    - { filesystem: '/tank/nfs/share',              mountpoint: '/nfs/tank/share',    type: 'none', options: 'bind',              dump: '0', pass: '0' }
    - { filesystem: '/tank/nfs/scratch',            mountpoint: '/nfs/tank/scratch',  type: 'none', options: 'bind',              dump: '0', pass: '0' }
    - { filesystem: '10.98.0.7:/cistern/nfs/home',  mountpoint: '/nfs/cistern/home',  type: 'nfs',  options: 'vers=4.0,soft,nodev',        dump: '0', pass: '0' }
    - { filesystem: '10.98.0.7:/cistern/nfs/files', mountpoint: '/nfs/cistern/files', type: 'nfs',  options: 'vers=4.0,soft,nodev,nosuid', dump: '0', pass: '0' }
    - { filesystem: '10.98.0.7:/cistern/nfs/share', mountpoint: '/nfs/cistern/share', type: 'nfs',  options: 'vers=4.0,soft,nodev,nosuid', dump: '0', pass: '0' }
    - { filesystem: '10.98.0.8:/keg/nfs/share',     mountpoint: '/nfs/keg/share',     type: 'nfs',  options: 'vers=4.0,soft,nodev,nosuid', dump: '0', pass: '0' }
  when: inventory_hostname == 'cyberdelia.vtluug.org'
  tags: needs_freeipa

- name: Mount NFS  (Dirtycow)
  mount:
    src: "{{ item.filesystem }}"
    path: "{{ item.mountpoint }}"
    fstype: "{{ item.type }}"
    opts: "{{ item.options }}"
    state: present
  with_items:
    - { filesystem: '10.98.0.6:/tank/nfs/share',   mountpoint: '/nfs/tank/share',    type: 'nfs',  options: 'vers=4.0,soft,nodev,nosuid', dump: '0', pass: '0' }
    - { filesystem: '10.98.0.6:/tank/nfs/scratch', mountpoint: '/nfs/tank/scratch',  type: 'nfs',  options: 'vers=4.0,soft,nodev,nosuid', dump: '0', pass: '0' }
    - { filesystem: '/cistern/nfs/home',           mountpoint: '/nfs/cistern/home',  type: 'none', options: 'bind',              dump: '0', pass: '0' }
    - { filesystem: '/cistern/nfs/files',          mountpoint: '/nfs/cistern/files', type: 'none', options: 'bind',              dump: '0', pass: '0' }
    - { filesystem: '/cistern/nfs/share',          mountpoint: '/nfs/cistern/share', type: 'none', options: 'bind',              dump: '0', pass: '0' }
    - { filesystem: '10.98.0.8:/keg/nfs/share',    mountpoint: '/nfs/keg/share',     type: 'nfs',  options: 'vers=4.0,soft,nodev,nosuid', dump: '0', pass: '0' }
  when: inventory_hostname == 'dirtycow.vtluug.org'
  tags: needs_freeipa

- name: Mount NFS  (Shellshock)
  mount:
    path: "{{ item.mountpoint }}"
    src: "{{ item.filesystem }}"
    fstype: "{{ item.type }}"
    opts: "{{ item.options }}"
    state: present
  with_items:
    - { filesystem: '10.98.0.6:/tank/nfs/share',    mountpoint: '/nfs/tank/share',    type: 'nfs',  options: 'vers=4.0,soft,nodev,nosuid', dump: '0', pass: '0' }
    - { filesystem: '10.98.0.6:/tank/nfs/scratch',  mountpoint: '/nfs/tank/scratch',  type: 'nfs',  options: 'vers=4.0,soft,nodev,nosuid', dump: '0', pass: '0' }
    - { filesystem: '10.98.0.7:/cistern/nfs/home',  mountpoint: '/nfs/cistern/home',  type: 'nfs',  options: 'vers=4.0,soft,nodev',        dump: '0', pass: '0' }
    - { filesystem: '10.98.0.7:/cistern/nfs/files', mountpoint: '/nfs/cistern/files', type: 'nfs',  options: 'vers=4.0,soft,nodev,nosuid', dump: '0', pass: '0' }
    - { filesystem: '10.98.0.7:/cistern/nfs/share', mountpoint: '/nfs/cistern/share', type: 'nfs',  options: 'vers=4.0,soft,nodev,nosuid', dump: '0', pass: '0' }
    - { filesystem: '/keg/nfs/share',               mountpoint: '/nfs/keg/share',     type: 'none', options: 'bind',              dump: '0', pass: '0' }
  when: inventory_hostname == 'shellshock.vtluug.org'
  tags: needs_freeipa

- name: Mount NFS (Sczi)
  mount:
    src: "{{ item.filesystem }}"
    path: "{{ item.mountpoint }}"
    fstype: "{{ item.type }}"
    opts: "{{ item.options }}"
    state: mounted
  with_items:
    - { filesystem: '10.98.0.7:/cistern/nfs/docker/data',   mountpoint: '/nfs/cistern/docker/data',   type: 'nfs', options: 'vers=4.0,soft,nodev,nosuid', dump: '0', pass: '0' }
    - { filesystem: '10.98.0.7:/cistern/nfs/srv',           mountpoint: '/nfs/cistern/srv',           type: 'nfs', options: 'vers=4.0,soft,nodev,nosuid', dump: '0', pass: '0' }
  when: inventory_hostname == 'sczi2.vtluug.org'
  tags: needs_freeipa
