---
- name: Create DANGEROUS alias
  lineinfile:
    path: /etc/sudoers
    insertafter: '^# Cmnd alias specification$'
    line: 'Cmnd_Alias DANGEROUS = /sbin/shutdown,/sbin/reboot,/sbin/halt,/sbin/poweroff'
    backup: yes
    validate: 'visudo -cf %s'

- name: Allow papatux to do anything
  lineinfile:
    path: /etc/sudoers
    line: 'papatux ALL=(ALL:ALL) NOPASSWD:ALL'
    backup: yes
    validate: 'visudo -cf %s'

- name: Prevent sudo group (besides papatux) from reboot/shutdown etc
  lineinfile:
    path: /etc/sudoers
    regexp: '^(%sudo\tALL=\(ALL:ALL\) ALL)$'
    line: '\1, !DANGEROUS'
    backrefs: yes
    backup: yes
    validate: 'visudo -cf %s'
