---
- name: Disable root ssh
  lineinfile:  
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin yes$'
    line: 'PermitRootLogin without-password'
    backrefs: yes
    backup: yes
  notify: Restart sshd
