---
- name: Configure sudo (RedHat)
  import_role:
    name: ansible-sudoers
  vars:
    sudoer_rewrite_sudoers_file: yes
    sudoer_aliases:
      command:
        - name: DANGEROUS
          comment: DANGEROUS commands
          commands:
            - /usr/sbin/shutdown
            - /usr/sbin/reboot
            - /usr/sbin/halt
            - /usr/sbin/poweroff
    sudoer_specs:
      - { name: 'wheel_restrictions',    comment: 'Special wheel restrictions',    users: '%wheel',     hosts: 'ALL', operators: 'ALL', tags: 'NOPASSWD', commands: 'ALL' }
      - { name: 'officers_restrictions', comment: 'Special officers restrictions', users: '%officers',  hosts: 'ALL', operators: 'ALL', tags: 'NOPASSWD', commands: 'ALL, !DANGEROUS' }
  when: ansible_os_family == 'RedHat'
  tags: needs_freeipa

- name: Configure sudo (Debian)
  import_role:
    name: ansible-sudoers
  vars:
    sudoer_rewrite_sudoers_file: yes
    sudoer_aliases:
      command:
        - name: DANGEROUS
          comment: DANGEROUS commands
          commands:
            - /sbin/shutdown
            - /sbin/reboot
            - /sbin/halt
            - /sbin/poweroff
    sudoer_specs:
      - { name: 'sudo_restrictions',     comment: 'Special sudo restrictions',     users: '%sudo',      hosts: 'ALL', operators: 'ALL', tags: 'NOPASSWD', commands: 'ALL' }
      - { name: 'officers_restrictions', comment: 'Special officers restrictions', users: '%officers',  hosts: 'ALL', operators: 'ALL', tags: 'NOPASSWD', commands: 'ALL, !DANGEROUS' }
  when: ansible_os_family == 'Debian'
  tags: needs_freeipa
