---
- name: Add papatux to libvirt group
  user:
    name: papatux
    groups: libvirt
    append: yes

- name: Start and enable luug_iptables_libvirt
  systemd:
    name: luug_iptables_libvirt.service
    state: started
    enabled: yes
