---
- name: Install common packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
  - curl
  - dpkg-dev
  - git
  - htop
  - man
  - nmap
  - ntp
  - tmux
  - vim
  - wget
  - zsh

#- name: Install freeipa-client
