---
- name: Install common packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - apt-listchanges
  - curl
  - git
  - htop
  - man
  - nmap
  - ntp
  - tmux
  - unattended-upgrades
  - vim
  - wget
  - zsh
